CONTRACTION_MAP = {
    "don't": "do not",
    "can't": "cannot",
    "won't": "will not",
    "shan't": "shall not",
    "i'm": "i am",
    "you're": "you are",
    "he's": "he is",
    "she's": "she is",
    "it's": "it is",
    "we're": "we are",
    "they're": "they are",
    "i've": "i have",
    "you've": "you have",
    "we've": "we have",
    "they've": "they have",
    "i'd": "i would",
    "you'd": "you would",
    "he'd": "he would",
    "she'd": "she would",
    "we'd": "we would",
    "they'd": "they would",
    "i'll": "i will",
    "you'll": "you will",
    "he'll": "he will",
    "she'll": "she will",
    "we'll": "we will",
    "they'll": "they will",
    "isn't": "is not",
    "aren't": "are not",
    "wasn't": "was not",
    "weren't": "were not",
    "hasn't": "has not",
    "haven't": "have not",
    "hadn't": "had not",
    "doesn't": "does not",
    "didn't": "did not",
    "couldn't": "could not",
    "shouldn't": "should not",
    "wouldn't": "would not",
    "mightn't": "might not",
    "mustn't": "must not",
    "let's": "let us",
    "that's": "that is",
    "who's": "who is",
    "what's": "what is",
    "here's": "here is",
    "there's": "there is",
    "when's": "when is",
    "where's": "where is",
    "why's": "why is",
}

SLANG_MAP = {
    "brb": "be right back",
    "lol": "laughing out loud",
    "omg": "oh my god",
    "ttyl": "talk to you later",
    "idk": "i do not know",
    "smh": "shaking my head",
    "btw": "by the way",
    "imo": "in my opinion",
    "fyi": "for your information",
    "lmk": "let me know",
    "lmao": "laughing",
    "rofl": "laughing",
    "thx": "thanks",
    "ty": "thank you",
    "np": "no problem",
    "wyd": "what are you doing",
    "ikr": "i know right",
    "tbh": "to be honest",
    "afk": "away from keyboard",
    "bff": "best friends forever",
    "dm": "direct message",
    "ftw": "for the win",
    "gg": "good game",
    "irl": "in real life",
    "jk": "just kidding",
    "nvm": "never mind",
    "ppl": "people",
    "sry": "sorry",
    "wbu": "what about you",
    "yw": "you are welcome",
    "xoxo": "hugs and kisses",
    "rt": "retweet",
    "fav": "favorite",
    "u": "you"
}
